name: Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'src/**'
      - 'test/**'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'src/**'
      - 'test/**'

jobs:
  api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        working-directory: .
        run: npm i

      - name: Execute unit tests
        working-directory: .
        run: npm run test